sudo: required
dist: trusty
language: node_js
node_js:
  - "4.5.0"
  - "6.9.5"
services:
  - postgresql
before_script:
  - psql -c 'drop database if exists docman_test;' -U postgres
  - psql -c 'create database docman_test;' -U postgres
script:
  - npm test
addons:
  postgresql: "9.3"